spring:
  application:
    name: Blogger

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-demo
    username: postgres
    password: password

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true